query Repos(
  $first: Int
  $last: Int
  $endCursor: String
  $startCursor: String
  $query: String!
) {
  search(
    query: $query
    type: REPOSITORY
    first: $first
    last: $last
    after: $endCursor
    before: $startCursor
  ) {
    repoCount: repositoryCount
    pageInfo {
      hasNextPage
      endCursor
      hasPreviousPage
      startCursor
    }
    repos: edges {
      repo: node {
        ... on Repository {
          id
          name
          pullRequests(first: 100, states: OPEN) {
            totalCount
          }
          vulnerabilityAlerts(first: 100) {
            totalCount
          }
        }
      }
    }
  }
}
