query RepoVulnerabilities($id: ID!) {
  node(id: $id) {
    ... on Repository {
      name
      id
      vulnerabilityAlerts(first: 100) {
        edges {
          node {
            createdAt
            id
            securityAdvisory {
              id
              severity
              summary
              description
              permalink
              publishedAt
            }
          }
        }
      }
    }
  }
}
